eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: alibou
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0


##Tutti i servizi si registrano su Eureka (che gira su localhost:8761) per farsi scoprire.
#
#Si collegano al Config Server per ottenere la configurazione centralizzata.